export const HANDLE_WEBSOCKET_CONNECT = 'HANDLE_WEBSOCKET_CONNECT';
export const HANDLE_WEBSOCKET_CONNECTED = 'HANDLE_WEBSOCKET_CONNECTED';
export const HANDLE_WEBSOCKET_DISCONNECT = 'HANDLE_WEBSOCKET_DISCONNECT';
export const HANDLE_WEBSOCKET_DISCONNECTED = 'HANDLE_WEBSOCKET_DISCONNECTED';
export const HANDLE_WEBSOCKET_MESSAGE = 'HANDLE_WEBSOCKET_MESSAGE';
